#! /bin/sh

#sleep 300
sleep 30
while sin | grep -q dmserver
do
    #rtc -sl hw
	netmap -m "u $1"
	if sin -n$1 | grep -q idle 
		then : #on -f $1 rtc -sl hw
		else 
			echo "\aNode $1 not visible"
			date
			netmap -m "m $1"
			echo "\a"
	fi
	sleep 60
done
