#!/bin/sh

case $NODE in

    1)  if sin -n1 | grep dmserver
            then echo Found dmserver on Node 1
        elif sin -n2 | grep dmserver
            then echo Found dmserver on Node 2
        else
            #slay olwm
         #/prim_fi/bin/sl &
            /Dmon/bin/dmfontload /prim_fi/monitor/cfg/fonts.cfg
            /Dmon/bin/dmserver /prim_fi/config/server1.ini &
            /prim_fi/START/chknet 2 &
            /prim_fi/START/archrm &
            #sleep 60
            #slay dmprhp
            #/prim_fi/bin/print_hotkey &
            #slay -s SIGHUP chain
        fi;;

    2)  if sin -n1 | grep dmserver
            then echo Found dmserver on Node 1
        elif sin -n2 | grep dmserver
            then echo Found dmserver on Node 2
        else
            #slay olwm
         #/prim_fi/bin/sl &
            /Dmon/bin/dmfontload /prim_fi/monitor/cfg/fonts.cfg
            /Dmon/bin/dmserver /prim_fi/config/server2.ini &
            /prim_fi/START/chknet 1 &
            /prim_fi/START/archrm &
            #sleep 60
            #slay dmprhp
            #/prim_fi/bin/print_hotkey &
            #slay -s SIGHUP chain
        fi;;

    3)  if sin -n3 | grep dmserver
            then echo Found dmserver on Node 3
        elif sin -n4 | grep dmserver
            then echo Found dmserver on Node 4
        else
            #slay olwm
         #/prim_fi/bin/sl &
            /Dmon/bin/dmfontload /prim_fi/monitor/cfg/fonts.cfg
            /Dmon/bin/dmserver /prim_fi/config/server3.ini &
            /prim_fi/START/chknet 4 &
            /prim_fi/START/archrm &
            #sleep 60
            #slay dmprhp
            #/prim_fi/bin/print_hotkey &
            #slay -s SIGHUP chain
        fi;;

    4)  if sin -n3 | grep dmserver
            then echo Found dmserver on Node 3
        elif sin -n4 | grep dmserver
            then echo Found dmserver on Node 4
        else
            #slay olwm
         #/prim_fi/bin/sl &
            /Dmon/bin/dmfontload /prim_fi/monitor/cfg/fonts.cfg
            /Dmon/bin/dmserver /prim_fi/config/server4.ini &
            /prim_fi/START/chknet 3 &
            /prim_fi/START/archrm &
            #sleep 60
            #slay dmprhp
            #/prim_fi/bin/print_hotkey &
            #slay -s SIGHUP chain
        fi;;

    5)  if sin -n1 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview1_5.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon1_5.ini &
                    sleep 2
                    ln -f -s //1/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //1/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //1/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview1_5.ini &
        elif sin -n2 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview2_5.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon2_5.ini &
                    sleep 2
                    ln -f -s //2/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //2/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //2/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview2_5.ini &
        elif sin -n3 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview3_5.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon3_5.ini &
                    sleep 2
                    /Dmon/bin/dmeventview   /prim_fi/config/evview3_5.ini &
                    ln -f -s //3/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //3/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //3/prim_fi_data/logger /prim_fi_data/logger
        elif sin -n4 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview4_5.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon4_5.ini &
                    sleep 2
                    ln -f -s //4/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //4/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //4/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview4_5.ini &
        else echo no running servers found
        fi;;

    6)  if sin -n1 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview1_6.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon1_6.ini &
                    sleep 2
                    ln -f -s //1/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //1/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //1/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview1_6.ini &
        elif sin -n2 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview2_6.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon2_6.ini &
                    sleep 2
                    ln -f -s //2/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //2/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //2/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview2_6.ini &
        elif sin -n3 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview3_6.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon3_6.ini &
                    sleep 2
                    /Dmon/bin/dmeventview   /prim_fi/config/evview3_6.ini &
                    ln -f -s //3/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //3/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //3/prim_fi_data/logger /prim_fi_data/logger
        elif sin -n4 | grep dmserver
            then    /Dmon/bin/dmmsgview       /prim_fi/config/msgview4_6.ini &
                    sleep 2
                    /Dmon/bin/dmmonitor       /prim_fi/config/mon4_6.ini &
                    sleep 2
                    ln -f -s //4/prim_fi_data/event /prim_fi_data/event
                    ln -f -s //4/prim_fi_data/archive /prim_fi_data/archive
                    ln -f -s //4/prim_fi_data/logger /prim_fi_data/logger
                    /Dmon/bin/dmeventview   /prim_fi/config/evview4_6.ini &
        else echo no running servers found
        fi;;

    *)  if sin | grep dmserver
            then echo Found dmserver
        else
            #slay olwm
         #/prim_fi/bin/sl &
            /Dmon/bin/dmserver /prim_fi/config/server.ini &
            #/prim_fi/START/chknet 2 &
            #/prim_fi/START/archrm &
            #sleep 60
            #slay -s SIGHUP chain
        fi;;
        #echo another NODE ;;

esac

